version: 0.7.{build}
pull_requests:
  do_not_increment_build_number: true
image:
- Ubuntu1804
- Visual Studio 2019 Preview

skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/

cache:
  - '%APPVEYOR_BUILD_FOLDER%\build'

environment:
  global:
    CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
    CMAKE_BUILD_TYPE: Release

install:
  - cmd : call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd : conda config --add channels conda-forge --force
  - cmd : conda install --yes --quiet cmake flang jom
  - cmd : call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cmd : set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
  - cmd : set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%"
  - sh :  sudo apt-get -y install cmake
  - sh :  sudo apt-get -y install cmake-data
  - sh :  sudo apt-get -y install gfortran


before_build:
  - ps: if (-Not (Test-Path .\build)) { mkdir build } else { Remove-Item .\build -Force -Recurse; mkdir build}
  - cd build
  - cmd : cmake -G "NMake Makefiles JOM" -DCMAKE_Fortran_COMPILER=flang -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON ..
  - 

build_script:
  - cmd : cmake --build .
  - sh : cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCBLAS:BOOL=ON -DLAPACKE:BOOL=ON -DBUILD_TESTING=ON -DLAPACKE_WITH_TMG:BOOL=ON .. 
after_build:
  - pwsh: "&($env:APPVEYOR_BUILD_FOLDER + '/compressLibs.ps1')"

artifacts:
  - path: artLibs.zip
    name: LAPACK_DLLS
test_script:
  - ctest -j2
